# video-aspect-override=4:3
panscan=1.0

# Force mpv to constantly output silent audio even when paused, 
# preventing your sound card or HDMI receiver from going to sleep.
audio-stream-silence=yes

# Tell mpv to wait a specific number of seconds after opening the 
# audio device before sending actual video/audio data. 
# (Adjust 1.5 to 1.0 or 2.0 depending on your hardware's wake time)
audio-wait-open=0.5
